"""
demo.py

Script Functionality:
This script acts as the entrypoint testing application (demonstration block) for benchmarking. 
It retrieves an experimental config object via the system's central generic factory and applies 
it directly to the unified benchmark workflow orchestrator to automatically perform all steps.

Logical Architecture:
- Configuration Initialization: Fetches intention schemas from ConfigFactory.
- Workflow Execution: Yields the execution control to the encapsulated `run_benchmark_workflow` logic block.
"""

from typing import Dict, Any

from egm.suites.config_factory import generate_configuration
from egm.suites.benchmark_workflow import run_benchmark_workflow

def main() -> None:
    """
    Main demonstration entry point triggering the full benchmark sequence.
    Demonstrates both explicit user parameters and implicit adaptive upper-level calls.
    """
    
    # =====================================================================
    # PSEUDO-CODE: Unifying State Tracking (plan_id)
    # The application layer provides a master execution tracking ID which propagates
    # top-down through all generation, simulation, semantics, and reporting stages.
    # =====================================================================
    global_plan_id = "EGM_MASTER_EXECUTION_001"
    
    print("\n" + "="*50)
    print(f">>> [Demo] SCENARIO 1: Workflow triggered by Direct User Intent [{global_plan_id}]")
    print("="*50)
    
    # The user constructs the semantic boundaries of their execution manually
    custom_intent = {
        "backend_choice": "QPU",
        "bundles": [
            {"protocol": "RB", "qubits": [[0, 1], [2, 3]], "depth": [2, 4, 8]},
            {"protocol": "XEB", "qubits": [[0, 1], [2, 3]], "depth": [2, 4, 8]}
        ]
    }
    
    # Generate the configuration passing the explicit parameters and master traceability ID
    config_direct = generate_configuration(
        mode="direct", 
        plan_id=global_plan_id, 
        intent_dict=custom_intent
    )
    
    # Launch the benchmarking suite orchestrator
    reports_direct = run_benchmark_workflow(config_direct)
    print(">>> Scenario 1 fully executed.\n")


    # =====================================================================
    # PSEUDO-CODE: Demonstration 2 - Adaptive Upper-Level Call
    # Simulates an external system querying hardware (like calibration loops)
    # automatically translating into benchmarking orchestration.
    # =====================================================================
    print("="*50)
    print(f">>> [Demo] SCENARIO 2: Workflow triggered via Adaptive Hardware Call [{global_plan_id}]")
    print("="*50)
    
    # Adaptive trigger parameters generated by simulated upper layers
    adaptive_trigger = "get_gate_error"
    adaptive_params = {
        "gate": "CZ",
        "qubits": [[0, 1], [2, 3]]
    }
    
    # Generate the configuration by informing the factory of the origin call
    config_adaptive = generate_configuration(
        mode="adaptive", 
        plan_id=global_plan_id,
        call_name=adaptive_trigger, 
        hardware_kwargs=adaptive_params
    )
    
    # Launch identical benchmarking suite orchestrator using adaptive schema
    reports_adaptive = run_benchmark_workflow(config_adaptive)
    print(">>> Scenario 2 fully executed.")
    
    print("\n>>> [Demo Application] Demonstration script completed successfully.\n")

if __name__ == "__main__":
    main()