# errorgnomark/analysis/__init__.py

"""
ErrorGnoMark Analysis Package

This package contains all modules and sub-packages related to the analysis
of data generated by quantum experiments. It is structured to mirror the
'experiments' package.

Sub-packages:
- benchmarking: Analysis for benchmarking protocols like Randomized Benchmarking.
- characterization: Analysis for device characterization experiments (T1, T2, SPAM, etc.).

Usage:
    from errorgnomark.analysis.characterization import fit_t1_decay
    from errorgnomark.analysis.benchmarking import fit_rb_decay
"""

# This top-level __init__.py is kept clean to encourage users to import
# directly from the more specific sub-packages (e.g., analysis.characterization).
# This avoids polluting the namespace and makes the code more readable.